#!/usr/bin/env bash
# =============================================================================
# install-hooks.sh — Git Pre-commit Hook Installer
#
# Purpose : Write a pre-commit hook that runs all three Promise lint scripts.
#           A failing lint blocks the commit, protecting Promise integrity
#           at the earliest possible point in the development cycle.
#
# Hooks installed:
#   .git/hooks/pre-commit  — runs check-privacy, check-data-sovereignty,
#                            check-no-subscription on every commit attempt.
#
# Usage   : ./scripts/install-hooks.sh [git-repo-root]
#           git-repo-root defaults to the parent of scripts/.
#
# Exit    : 0 = hook installed successfully, 1 = error
# =============================================================================
set -euo pipefail

# ── Colours ────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[PASS]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
fail()  { echo -e "${RED}[FAIL]${NC} $*"; }
header(){ echo -e "\n${YELLOW}==> $*${NC}"; }

# ── Config ──────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${1:-$(cd "${SCRIPT_DIR}/.." && pwd)}"
GIT_DIR="${REPO_ROOT}/.git"
HOOKS_DIR="${GIT_DIR}/hooks"
HOOK_FILE="${HOOKS_DIR}/pre-commit"

# ── Validation ──────────────────────────────────────────────────────────────
header "Installing Promise Lint Pre-commit Hook"

if [[ ! -d "$GIT_DIR" ]]; then
  fail "No .git directory found at: $REPO_ROOT"
  echo "       Run this script from inside a git repository."
  exit 1
fi

# Verify lint scripts exist
for script in check-privacy.sh check-data-sovereignty.sh check-no-subscription.sh; do
  if [[ ! -f "${SCRIPT_DIR}/${script}" ]]; then
    fail "Missing lint script: ${SCRIPT_DIR}/${script}"
    echo "       Ensure all three lint scripts are present before installing hooks."
    exit 1
  fi
done

mkdir -p "$HOOKS_DIR"

# ── Backup existing hook ────────────────────────────────────────────────────
if [[ -f "$HOOK_FILE" ]]; then
  backup="${HOOK_FILE}.bak.$(date +%Y%m%d_%H%M%S)"
  warn "Existing pre-commit hook found. Backing up to: $backup"
  mv "$HOOK_FILE" "$backup"
fi

# ── Write hook ───────────────────────────────────────────────────────────────
# REPO_ROOT and SCRIPT_DIR are baked in at install time for reliability.
cat > "$HOOK_FILE" <<HOOK_EOF
#!/usr/bin/env bash
# =============================================================================
# pre-commit hook — Promise Lint Gate
#
# Auto-generated by install-hooks.sh on $(date '+%Y-%m-%d %H:%M:%S')
# Source: ${SCRIPT_DIR}/install-hooks.sh
#
# DO NOT EDIT MANUALLY. Re-run install-hooks.sh to regenerate.
# =============================================================================
set -euo pipefail

SCRIPTS_DIR="${SCRIPT_DIR}"
SOURCE_ROOT="${REPO_ROOT}"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'

echo -e "\${YELLOW}[pre-commit] Running Promise Lint...${NC}"
echo ""

FAILED=0

run_lint() {
  local script="\$1"
  local label="\$2"
  if bash "\${SCRIPTS_DIR}/\${script}" "\${SOURCE_ROOT}"; then
    echo -e "\${GREEN}[pre-commit] \${label}: PASSED\${NC}"
  else
    echo -e "\${RED}[pre-commit] \${label}: FAILED${NC}"
    FAILED=1
  fi
  echo ""
}

run_lint "check-privacy.sh"          "Privacy (External Host Whitelist)"
run_lint "check-data-sovereignty.sh" "Data Sovereignty (Export Capability)"
run_lint "check-no-subscription.sh"  "No-Subscription (GOVERNANCE §5)"

if [[ \$FAILED -ne 0 ]]; then
  echo -e "\${RED}[pre-commit] Commit BLOCKED — one or more Promise lint checks failed.\${NC}"
  echo ""
  echo "  Fix the violations above, then re-stage and commit."
  echo "  To skip (emergency only): git commit --no-verify"
  echo "  Note: --no-verify bypasses lint; you are responsible for the Promise."
  echo ""
  exit 1
fi

echo -e "\${GREEN}[pre-commit] All Promise lints PASSED. Proceeding with commit.\${NC}"
exit 0
HOOK_EOF

chmod +x "$HOOK_FILE"

# ── Verify ──────────────────────────────────────────────────────────────────
if [[ -x "$HOOK_FILE" ]]; then
  info "Pre-commit hook installed: $HOOK_FILE"
  echo ""
  echo "  Hooks active:"
  echo "    check-privacy.sh          — External Host Whitelist"
  echo "    check-data-sovereignty.sh — Encodable + VersionedSchema + CSV export"
  echo "    check-no-subscription.sh  — GOVERNANCE §5 Subscription Block"
  echo ""
  echo "  The hook runs automatically on every 'git commit'."
  echo "  Emergency bypass: 'git commit --no-verify' (logs your responsibility)."
else
  fail "Hook file not executable: $HOOK_FILE"
  exit 1
fi
